### ISSUE TITLE
Add `GetEndorsements` method

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa-proto#36]

**Comment by jwmdev** [comment]
This issue is  already implemented. Can it be closed?

**Comment by aoudiamoncef** [comment]
It's not implemented, it's just specified. The dev are in progress

**Comment by aoudiamoncef** [comment]
For the SDK, don't use the main branch at the moment. Use a specific commit rev which matches the testnet release. 

We'll improve this mainnet by using tags 🏷️. Of fir the next testnet we'll stérât a align the tags 🏷️ with the version of Massa.
