### ISSUE TITLE
Operation submission is impractical

### ISSUE THREAD

**Issue by damip** [massalabs/massa-proto#52]
Currently, to submit an operation in GRPC we need to:
* create the operation, serialize it in its low level format [publicKey, operation_contents]
* sign the the data
* assemble a whole SecureShare:
  * deduce the creator address and serialize it as string
  * re-serialize the creator public key as string
  * re-serialize the secure_hash in text format
* call the GRPC send operation with all those parameters

What would be way more usable:
* create the operation, serialize it in its low level format [publicKey, operation_contents]
* sign the data
* call the GRPC send operation only with the concatenation  [signature, publicKey, operation_contents] like it is done here: https://github.com/massalabs/massa/blob/main/massa-models/src/secure_share.rs#L113-L123

And more generally, when retrieving operations, no need to destructure them into SecureShare, we can just keep them in their low level  [signature, publicKey, operation_contents] format.

**Comment by aoudiamoncef** [comment]
@damip 

SecureShare will be replaced by Vec<u8> and It's over ? 

We'll do this for testnet 26 ?

**Comment by damip** [comment]
can you double-check that it does not break any existing projects/tooling ?

**Comment by aoudiamoncef** [comment]
@damip It seems that the gRPC API is not wide spread yet, I made a small message to builders just in case.
